# This workflow will build the project on pull requests with tests
# Uses:
#   OS: ubuntu-latest
#   JDK: Adopt JDK 8

name: Maven

on:
  push:
    branches: ["main", "dev*", "dev/*", "fix*", "fix/*"]
    tags: ["*.*.*"]

env:
  MAVEN_OPTS: -Xmx4g -Xms1g

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Adopt JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: "8"
          distribution: "adopt"

      - name: Cache local Maven repository
        id: cache-maven-m2
        uses: actions/cache@v2
        env:
          cache-name: cache-m2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ env.cache-name }}-
            ${{ runner.os }}-maven-
            ${{ runner.os }}-

      - name: Build with Maven
        run: mvn clean install -U -B
      
      - name: Azure Login
        if: ${{ success() }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        if: ${{ success() && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/heads/dev')) }}
        env:
          CONTAINER: github-actions
          PREFIX: wso2-extensions/identity-oauth2-grant-token-exchange
        run: |
          az storage blob upload-batch --auth-mode login --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} --destination ${{ env.CONTAINER }} --destination-path ${{ env.PREFIX }} --source /home/runner/work/identity-oauth2-grant-token-exchange/identity-oauth2-grant-token-exchange/feature/org.wso2.carbon.identity.oauth2.grant.token.exchange.feature/target --pattern *.zip --overwrite --no-progress
